### 1. false
GET http://localhost:8080/booking/api/bookings/check?customerId=1&roomId=1


### 2. 409 conflict
POST http://localhost:8083/api/reviews
Content-Type: application/json

{
  "customerId": 1,
  "roomId": 1,
  "rating": 5,
  "comment": "Bra rum"
}

