spring.application.name=pensionat-kademina-rating-service

spring.jpa.hibernate.ddl-auto=update

booking-service.url=${BOOKING_SERVICE_URL:http://booking-service:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:rating_db}}
spring.datasource.username=${MYSQLUSER:springUser}
spring.datasource.password=${MYSQLPASSWORD:secretPassword}
