spring.application.name=pensionat-kademina-rating-service
server.port=8083

spring.jpa.hibernate.ddl-auto=update

booking-service.url=${BOOKING_SERVICE_URL:http://localhost:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rating_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springUser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretPassword}